
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 20 14:44:18 CET 2016
//----------------------------------------------------

package mj_compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 37;
  public static final int ASSIGNDIV = 49;
  public static final int CONST = 4;
  public static final int CHAR = 19;
  public static final int ASSIGNMUL = 48;
  public static final int LPAREN = 43;
  public static final int SEMI = 7;
  public static final int CONTINUE = 17;
  public static final int ASSIGNMOD = 50;
  public static final int ASSIGNPLUS = 46;
  public static final int FOR = 16;
  public static final int MINUS = 25;
  public static final int RPAREN = 44;
  public static final int STATIC = 6;
  public static final int AND = 35;
  public static final int LT = 33;
  public static final int OR = 36;
  public static final int ASSIGNMINUS = 47;
  public static final int BOOL = 20;
  public static final int COMMA = 8;
  public static final int CLASS = 13;
  public static final int DIV = 27;
  public static final int GEQ = 32;
  public static final int PLUS = 24;
  public static final int ASSIGN = 45;
  public static final int IF = 22;
  public static final int DOT = 12;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 38;
  public static final int RETURN = 10;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int NUMBER = 18;
  public static final int MOD = 28;
  public static final int NEQ = 30;
  public static final int BREAK = 3;
  public static final int IDENT = 21;
  public static final int VOID = 11;
  public static final int EQ = 29;
  public static final int LBRACK = 41;
  public static final int LBRACE = 39;
  public static final int ELSE = 23;
  public static final int RBRACK = 42;
  public static final int READ = 5;
  public static final int RBRACE = 40;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int LEQ = 34;
  public static final int GT = 31;
  public static final int PRINT = 9;
}

