
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 26 20:03:48 CET 2016
//----------------------------------------------------

package mj_compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ASSIGNDIV = 44;
  public static final int CONST = 22;
  public static final int CHAR = 23;
  public static final int ASSIGNMUL = 43;
  public static final int LPAREN = 8;
  public static final int SEMI = 7;
  public static final int CONTINUE = 4;
  public static final int ASSIGNMOD = 45;
  public static final int ASSIGNPLUS = 41;
  public static final int FOR = 29;
  public static final int STATIC = 3;
  public static final int RPAREN = 9;
  public static final int AND = 31;
  public static final int LT = 35;
  public static final int OR = 30;
  public static final int ASSIGNMINUS = 42;
  public static final int BOOL = 24;
  public static final int COMMA = 10;
  public static final int CLASS = 20;
  public static final int INC = 27;
  public static final int DIV = 49;
  public static final int GEQ = 34;
  public static final int ASSIGN = 40;
  public static final int IF = 18;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int MUL = 48;
  public static final int ADD = 46;
  public static final int MOD = 50;
  public static final int NUMBER = 25;
  public static final int NEQ = 32;
  public static final int BREAK = 17;
  public static final int IDENT = 26;
  public static final int VOID = 13;
  public static final int EQ = 39;
  public static final int LBRACK = 14;
  public static final int LBRACE = 5;
  public static final int ELSE = 19;
  public static final int READ = 16;
  public static final int RBRACK = 15;
  public static final int RBRACE = 6;
  public static final int EXTENDS = 21;
  public static final int PROG = 2;
  public static final int LEQ = 36;
  public static final int DEC = 28;
  public static final int GT = 33;
  public static final int SUB = 47;
  public static final int PRINT = 11;
}

