
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 22 21:36:28 CET 2016
//----------------------------------------------------

package mj_compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ASSIGNDIV = 47;
  public static final int CONST = 25;
  public static final int CHAR = 26;
  public static final int ASSIGNMUL = 46;
  public static final int LPAREN = 8;
  public static final int SEMI = 7;
  public static final int CONTINUE = 4;
  public static final int ASSIGNMOD = 48;
  public static final int ASSIGNPLUS = 44;
  public static final int FOR = 32;
  public static final int MINUS = 14;
  public static final int STATIC = 3;
  public static final int RPAREN = 9;
  public static final int AND = 34;
  public static final int LT = 38;
  public static final int OR = 33;
  public static final int ASSIGNMINUS = 45;
  public static final int BOOL = 27;
  public static final int COMMA = 10;
  public static final int CLASS = 23;
  public static final int INC = 30;
  public static final int DIV = 52;
  public static final int GEQ = 37;
  public static final int PLUS = 13;
  public static final int ASSIGN = 43;
  public static final int IF = 21;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 15;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int MUL = 51;
  public static final int ADD = 49;
  public static final int MOD = 53;
  public static final int NUMBER = 28;
  public static final int NEQ = 35;
  public static final int BREAK = 20;
  public static final int IDENT = 29;
  public static final int VOID = 16;
  public static final int EQ = 42;
  public static final int LBRACK = 17;
  public static final int LBRACE = 5;
  public static final int ELSE = 22;
  public static final int READ = 19;
  public static final int RBRACK = 18;
  public static final int RBRACE = 6;
  public static final int EXTENDS = 24;
  public static final int PROG = 2;
  public static final int LEQ = 39;
  public static final int DEC = 31;
  public static final int GT = 36;
  public static final int SUB = 50;
  public static final int PRINT = 11;
}

